### ISSUE TITLE
Create Modulefile for S4

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/EMC_verif-global#115]
A modulefile should be created for S4 and module loading moved out of load_modules.sh.

**Comment by DavidHuber-NOAA** [comment]
@malloryprow I'm working on this now, so feel free to assign me.

**Comment by malloryprow** [comment]
@DavidHuber-NOAA Usually when the plotting jobs are running extremely so it is because of bad stats data (originating from the model analysis or model forecasts). If there is an very large difference between the model analysis and model forecast, this will cause potentially wide range of values for the stats, and the code is designed to iteratively adjust the y-axis to avoid the lines from being in the legend (so it is legible and clean). I've experienced this a few times before.

However, here I think the code might be struggling with the fact you are just plotting a single day. The code isn't really set up to just plot a single point since it really isn't useful and doesn't make sense statistically.

**Comment by DavidHuber-NOAA** [comment]
@malloryprow OK, that makes sense.  What would you consider to be the minimum period of time that makes sense?

**Comment by malloryprow** [comment]
3 days should be good

**Comment by InnocentSouopgui-NOAA** [comment]
@DavidHuber-NOAA,
Any update on this issue?
I can take it over if you have a lot of other things.
I have S4's users who are having trouble with the stand alone verif-global.

**Comment by DavidHuber-NOAA** [comment]
@InnocentSouopgui-NOAA Please feel free to take over.  I haven't been able to work on this for some time.
